### ISSUE TITLE
More example ?

### ISSUE THREAD

**Issue by GunGunGun** [ramikg/ssl-context-configurator#1]
Hi, can you provide more working examples because I used the example code from code page and got this error:

```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Python38\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Python38\lib\site-packages\urllib3\util\ssl_.py", line 454, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Python38\lib\site-packages\urllib3\util\ssl_.py", line 498, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Deve\BypassTlsFing\ssl-context-configurator-master\test.py", line 55, in <module>
    r = p.request('GET', 'https://tools.scrapfly.io/api/fp/ja3?extended=1')
  File "C:\Python38\lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
  File "C:\Python38\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Python38\lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='tools.scrapfly.io', port=443): Max retries exceeded with url: /api/fp/ja3?extended=1 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HAND
SHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
```

```

import urllib3
from ssl_context_configurator import SSLContextConfigurator

ssl_context = urllib3.util.ssl_.create_urllib3_context()

with SSLContextConfigurator(ssl_context, libssl_path='libssl.so') as ssl_context_configurator:
    ssl_context_configurator.configure_signature_algorithms('ECDSA+SHA256')

pool_manager = urllib3.PoolManager(cert_reqs='CERT_NONE', ssl_context=ssl_context)
pool_manager.request('GET', 'https://tools.scrapfly.io/api/fp/ja3?extended=1')
```

**Comment by GunGunGun** [comment]
Updated

I've managed to make it work, but it doesn't change my Signature Algorithms at all, this is my test:

```
import urllib3
from ssl_context_configurator import SSLContextConfigurator

ssl_context = urllib3.util.ssl_.create_urllib3_context()

with SSLContextConfigurator(ssl_context, libssl_path='libssl.so') as ssl_context_configurator:
    ssl_context_configurator.configure_signature_algorithms('ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512')

pool_manager = urllib3.PoolManager(cert_reqs='CERT_NONE', ssl_context=ssl_context)
r = pool_manager.request('GET', 'https://ja3er.com/json')
print(r.data)
```

Output:

```
C:\Python38\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ja3er.com'. Adding certificate verification is strongly advised. S
ee: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
b'{"ja3_hash":"15d8a8149f927592aac73a4ea4f721f4", "ja3": "771,4866-4867-4865-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-69-136-157-47-65-53-61-132-255,0-11-10-16-22-23-49-13-43-45-51-
21,29-23-1035-25-24,0-1-2", "User-Agent": "python-urllib3/1.26.9"}'
```


```
import urllib3
from ssl_context_configurator import SSLContextConfigurator

ssl_context = urllib3.util.ssl_.create_urllib3_context()

pool_manager = urllib3.PoolManager(cert_reqs='CERT_NONE', ssl_context=ssl_context)
r = pool_manager.request('GET', 'https://ja3er.com/json')
print(r.data)
```


Output:

```
C:\Python38\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ja3er.com'. Adding certificate verification is strongly advised. S
ee: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
b'{"ja3_hash":"15d8a8149f927592aac73a4ea4f721f4", "ja3": "771,4866-4867-4865-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-69-136-157-47-65-53-61-132-255,0-11-10-16-22-23-49-13-43-45-51-
21,29-23-1035-25-24,0-1-2", "User-Agent": "python-urllib3/1.26.9"}'
```


Still the same "ja3_hash":"15d8a8149f927592aac73a4ea4f721f4".

**Comment by ramikg** [comment]
The usage example changes the supported signature algorithms list, which is a TLS 1.2 extension.
JA3 doesn't hash the contents of (almost all) TLS extensions, but merely the list of extensions.

If you do want to affect the JA3 hash, you may try modifying the list of supported cipher suites (which JA3 does hash).  
As an example, here are two methods to remove the ECDSA cipher suites from the list:

1. Remove the ECDSA algorithms in your call to `ssl_context_configurator.configure_signature_algorithms`.
  This should have the effect of removing the ECDSA cipher suites.
2. Directly configure the list of supported cipher suites to be what you want.  
E.g. `ssl_context_configurator.configure_cipher_suite('DEFAULT:!ECDSA')`.
